export const AppointmentErrorCode = {
  APPOINTMENT_CONFLICT_POSTGRES: '23P01',
  APPOINTMENT_DOCTOR_CONFLICT: 'APPOINTMENT_DOCTOR_CONFLICT',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ALREADY_COMPLETED: 'ALREADY_COMPLETED',
  PATIENT_PLAN_MISMATCH: 'PATIENT_PLAN_MISMATCH',
  NOTE_TOO_LONG: 'NOTE_TOO_LONG',
  PRACTITIONER_REQUIRED: 'PRACTITIONER_REQUIRED',
  REOPEN_WINDOW_EXPIRED: 'REOPEN_WINDOW_EXPIRED',
  FORBIDDEN_REOPEN: 'FORBIDDEN_REOPEN',
  NOT_COMPLETED: 'NOT_COMPLETED',
  REOPEN_NO_ACTIVE_SESSION: 'REOPEN_NO_ACTIVE_SESSION',
} as const

export type AppointmentErrorCode = (typeof AppointmentErrorCode)[keyof typeof AppointmentErrorCode]
