export const InvoiceErrorCode = {
  INVALID_CLINIC_ID: 'INVALID_CLINIC_ID',
  CLINIC_SCOPE_MISMATCH: 'CLINIC_SCOPE_MISMATCH',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_CLINIC_MISMATCH: 'PATIENT_CLINIC_MISMATCH',
  TREATMENT_PLAN_NOT_FOUND: 'TREATMENT_PLAN_NOT_FOUND',
  TREATMENT_PLAN_CLINIC_MISMATCH: 'TREATMENT_PLAN_CLINIC_MISMATCH',
  PATIENT_PLAN_MISMATCH: 'PATIENT_PLAN_MISMATCH',
  TREATMENT_PLAN_CANCELLED: 'TREATMENT_PLAN_CANCELLED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  INVALID_LINE_ITEMS: 'INVALID_LINE_ITEMS',
  LINE_ITEM_DESCRIPTION_REQUIRED: 'LINE_ITEM_DESCRIPTION_REQUIRED',
  INVALID_LINE_ITEM_QUANTITY: 'INVALID_LINE_ITEM_QUANTITY',
  INVALID_LINE_ITEM_PRICE: 'INVALID_LINE_ITEM_PRICE',
  INVALID_INVOICE_TOTAL: 'INVALID_INVOICE_TOTAL',
  INVOICE_ALREADY_CREATED: 'INVOICE_ALREADY_CREATED',
  INVOICE_NUMBER_GENERATION_FAILED: 'INVOICE_NUMBER_GENERATION_FAILED',
  INVOICE_CREATE_RETRY_EXHAUSTED: 'INVOICE_CREATE_RETRY_EXHAUSTED',
  INVALID_CREATE_INVOICE_RESPONSE: 'INVALID_CREATE_INVOICE_RESPONSE',
} as const

export type InvoiceErrorCode = (typeof InvoiceErrorCode)[keyof typeof InvoiceErrorCode]
