export const PaymentErrorCode = {
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_STATUS_INVALID: 'INVOICE_STATUS_INVALID',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_INVOICE_TOTAL: 'INVALID_INVOICE_TOTAL',
  PAYMENT_EXCEEDS_OUTSTANDING: 'PAYMENT_EXCEEDS_OUTSTANDING',
  REFERENCE_NOTE_TOO_LONG: 'REFERENCE_NOTE_TOO_LONG',
  PAYMENT_ALREADY_RECORDED: 'PAYMENT_ALREADY_RECORDED',
  INVOICE_TOTAL_BELOW_PAID: 'INVOICE_TOTAL_BELOW_PAID',
} as const

export type PaymentErrorCode = (typeof PaymentErrorCode)[keyof typeof PaymentErrorCode]
